version: '3.3'
services:
  ams-webapp:
    image: terrabrasilis/ams-webapp:v1.2.0
    container_name: ams.webapp
    restart: always
    ports:
      - 81:7000
    environment:
      - "HOMOLOGATION=False"
      - "SCRIPT_NAME=/ams"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoams/"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams/"
    env_file:
      - webapp-secrets.env

  ams-sync:
    image: terrabrasilis/ams-sync:v1.2.0
    container_name: ams.sync
    restart: always
    volumes:
      - "/some/local/dir/data:/usr/local/data"
    environment:
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_lzw_4326.tif"
    env_file:
      - webapp-secrets.env
