version: '3.3'
services:
  ams-webapp:
    image: terrabrasilis/ams-webapp:vx.y.z
    container_name: ams.webapp
    restart: always
    ports:
      - 81:7000
    environment:
      - "SCRIPT_NAME=/ams"
      - "GEOSERVER_URL=http://terrabrasilis.dpi.inpe.br/geoams/"
      - "SERVER_NAME=terrabrasilis.dpi.inpe.br"
      - "APPLICATION_ROOT=/ams/"
    env_file:
      - frontend-secrets.env

  ams-sync-amazonia:
    image: terrabrasilis/ams-sync:vx.y.z
    container_name: ams.sync.amazonia
    restart: always
    volumes:
      - "/some/local/dir/data:/usr/local/data"
      - "/some/geoserver/datadir:/usr/local/data/geoserver"
    environment:
      - "BIOME=Amazônia"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2023.tif"
      - "ALL_DATA=True"
      - "RISK_OUTPUT_PATH=/usr/local/data"
    env_file:
      - amz-backend-secrets.env

  ams-sync-cerrado:
    image: terrabrasilis/ams-sync:vx.y.z
    container_name: ams.sync.cerrado
    restart: always
    volumes:
      - "/some/local/dir/data:/usr/local/data"
    environment:
      - "BIOME=Cerrado"
      - "INPUT_GEOTIFF_FUNDIARY_STRUCTURE=estrutura_fundiaria_cst_2023.tif"
      - "ALL_DATA=True"
    env_file:
      - cer-backend-secrets.env